/**
 * Evergreen and common keyword abilities the engine enforces natively.
 * Anything not listed is still tracked as text on the card so players can
 * apply it manually.
 */
export const ENFORCED_KEYWORDS = new Set([
  'Flying',
  'First strike',
  'Double strike',
  'Deathtouch',
  'Lifelink',
  'Trample',
  'Vigilance',
  'Haste',
  'Flash',
  'Defender',
  'Reach',
  'Menace',
  'Hexproof',
  'Indestructible',
  'Shroud',
  'Ward',
  'Protection',
  'Fear',
  'Intimidate',
  'Skulk',
  'Horsemanship',
  'Shadow',
  'Flanking',
  'Infect',
  'Wither',
  'Toxic',
  'Prowess',
  'Exalted',
  'Changeling',
  'Flashback',
  'Kicker',
  'Cycling',
  'Equip',
  'Enchant',
  'Landfall',
  'Undying',
  'Persist',
  'Convoke',
  'Affinity',
  'Cascade',
  'Storm',
  'Riot',
  'Unleash',
  'Evoke',
  'Buyback',
  'Rebound',
  'Unearth',
  'Escape',
  'Delve',
  'Improvise',
  'Emerge',
  'Bushido',
  'Rampage',
  'Annihilator',
  'Battle cry',
  'Exploit',
  'Extort',
  'Devoid',
  'Ingest',
  'Mentor',
  'Afflict',
  'Fabricate',
  'Crew',
  'Partner',
  'Companion',
  'Commander ninjutsu',
  'Ninjutsu',
  'Myriad',
  'Melee',
  'Dethrone',
  'Backup',
  'Training',
  'Decayed',
  'Disturb',
  'Daybound',
  'Nightbound',
  'Living weapon',
  'Modular',
  'Sunburst',
  'Scavenge',
  'Graft',
  'Bloodthirst',
  'Devour',
  'Undaunted',
  'Split second',
  'Suspend',
  'Vanishing',
  'Fading',
  'Cumulative upkeep',
  'Echo',
  'Morph',
  'Megamorph',
  'Disguise',
  'Manifest',
  'Miracle',
  'Madness',
  'Dredge',
  'Hideaway',
  'Landwalk',
  'Islandwalk',
  'Swampwalk',
  'Forestwalk',
  'Mountainwalk',
  'Plainswalk',
  'Offspring',
  'Impending',
  'Gift',
  'Bargain',
  'Casualty',
  'Blitz',
  'Connive',
  'Read ahead',
  'Enlist',
  'Ravenous',
  'Boast',
  'Foretell',
  'Squad',
  'Reconfigure',
  'Compleated',
  'For Mirrodin!',
  'Toxic',
  'Prototype',
  'Encore',
  'Mutate',
  'Escalate',
  'Surge',
  'Awaken',
  'Rally',
  'Cohort',
  'Renown',
  'Outlast',
  'Prowl',
  'Conspire',
  'Retrace',
  'Reinforce',
  'Champion',
  'Evolve',
  'Cipher',
  'Battalion',
  'Bestow',
  'Tribute',
  'Heroic',
  'Constellation',
  'Ferocious',
  'Raid',
  'Dash',
  'Bolster',
  'Rebound',
  'Menace',
  'Ingest',
  'Support',
  'Investigate',
  'Delirium',
  'Escalate',
  'Meld',
  'Energy',
  'Revolt',
  'Vehicle',
  'Improvise',
  'Aftermath',
  'Embalm',
  'Exert',
  'Eternalize',
  'Afflict',
  'Ascend',
  'Explore',
  'Jump-start',
  'Mentor',
  'Surveil',
  'Undergrowth',
  'Adapt',
  'Addendum',
  'Afterlife',
  'Riot',
  'Spectacle',
  'Amass',
  'Proliferate',
  'Adventure',
  'Food',
  'Mill',
  'Devotion',
  'Learn',
  'Ward',
  'Magecraft',
  'Cleave',
  'Alliance',
  'Coven',
  'Domain',
  'Hellbent',
  'Threshold',
  'Fateful hour',
  'Morbid',
  'Metalcraft',
  'Bloodrush',
  'Battle cry',
  'Inspired',
  'Strive',
  'Prowess',
  'Ingest',
  'Converge',
  'Devoid',
  'Council\'s dilemma',
  'Will of the council',
  'Lieutenant',
  'Parley',
  'Join forces',
  'Tempting offer',
  'Secret council',
]);

/** Keywords that change combat/damage math and are fully enforced. */
export const COMBAT_KEYWORDS = new Set(['Flying', 'First strike', 'Double strike', 'Deathtouch', 'Lifelink', 'Trample', 'Vigilance', 'Reach', 'Menace', 'Defender', 'Indestructible', 'Infect', 'Wither', 'Toxic', 'Fear', 'Intimidate', 'Skulk', 'Shadow', 'Horsemanship', 'Flanking']);

export function normalizeKeyword(k: string): string {
  const s = k.trim();
  return s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
}
