import type { TokenSpec } from './script.js';

/** Common predefined tokens referenced by name in scripts and compiled text. */
export const TOKEN_PRESETS: Record<string, TokenSpec> = {
  Treasure: {
    name: 'Treasure',
    typeLine: 'Artifact — Treasure',
    colors: [],
    oracleText: '{T}, Sacrifice this artifact: Add one mana of any color.',
  },
  Food: {
    name: 'Food',
    typeLine: 'Artifact — Food',
    colors: [],
    oracleText: '{2}, {T}, Sacrifice this artifact: You gain 3 life.',
  },
  Clue: {
    name: 'Clue',
    typeLine: 'Artifact — Clue',
    colors: [],
    oracleText: '{2}, Sacrifice this artifact: Draw a card.',
  },
  Blood: {
    name: 'Blood',
    typeLine: 'Artifact — Blood',
    colors: [],
    oracleText: '{1}, {T}, Discard a card, Sacrifice this artifact: Draw a card.',
  },
  Map: {
    name: 'Map',
    typeLine: 'Artifact — Map',
    colors: [],
    oracleText: '{1}, {T}, Sacrifice this artifact: Target creature you control explores. Activate only as a sorcery.',
  },
  Powerstone: {
    name: 'Powerstone',
    typeLine: 'Artifact — Powerstone',
    colors: [],
    oracleText: "{T}: Add {C}. This mana can't be spent to cast nonartifact spells.",
  },
  Gold: {
    name: 'Gold',
    typeLine: 'Artifact — Gold',
    colors: [],
    oracleText: 'Sacrifice this artifact: Add one mana of any color.',
  },
  Soldier: { name: 'Soldier', typeLine: 'Creature — Soldier', power: '1', toughness: '1', colors: ['W'] },
  Spirit: { name: 'Spirit', typeLine: 'Creature — Spirit', power: '1', toughness: '1', colors: ['W'], keywords: ['Flying'] },
  Zombie: { name: 'Zombie', typeLine: 'Creature — Zombie', power: '2', toughness: '2', colors: ['B'] },
  Goblin: { name: 'Goblin', typeLine: 'Creature — Goblin', power: '1', toughness: '1', colors: ['R'] },
  Elf: { name: 'Elf Warrior', typeLine: 'Creature — Elf Warrior', power: '1', toughness: '1', colors: ['G'] },
  Saproling: { name: 'Saproling', typeLine: 'Creature — Saproling', power: '1', toughness: '1', colors: ['G'] },
  Beast: { name: 'Beast', typeLine: 'Creature — Beast', power: '3', toughness: '3', colors: ['G'] },
  Elemental: { name: 'Elemental', typeLine: 'Creature — Elemental', power: '1', toughness: '1', colors: ['R'] },
  Thopter: { name: 'Thopter', typeLine: 'Artifact Creature — Thopter', power: '1', toughness: '1', colors: [], keywords: ['Flying'] },
  Servo: { name: 'Servo', typeLine: 'Artifact Creature — Servo', power: '1', toughness: '1', colors: [] },
  Insect: { name: 'Insect', typeLine: 'Creature — Insect', power: '1', toughness: '1', colors: ['G'] },
  Bird: { name: 'Bird', typeLine: 'Creature — Bird', power: '1', toughness: '1', colors: ['W'], keywords: ['Flying'] },
  Cat: { name: 'Cat', typeLine: 'Creature — Cat', power: '1', toughness: '1', colors: ['W'] },
  Human: { name: 'Human', typeLine: 'Creature — Human', power: '1', toughness: '1', colors: ['W'] },
  Knight: { name: 'Knight', typeLine: 'Creature — Knight', power: '2', toughness: '2', colors: ['W'], keywords: ['Vigilance'] },
  Wolf: { name: 'Wolf', typeLine: 'Creature — Wolf', power: '2', toughness: '2', colors: ['G'] },
  Bear: { name: 'Bear', typeLine: 'Creature — Bear', power: '2', toughness: '2', colors: ['G'] },
  Squirrel: { name: 'Squirrel', typeLine: 'Creature — Squirrel', power: '1', toughness: '1', colors: ['G'] },
  Rat: { name: 'Rat', typeLine: 'Creature — Rat', power: '1', toughness: '1', colors: ['B'] },
  Faerie: { name: 'Faerie Rogue', typeLine: 'Creature — Faerie Rogue', power: '1', toughness: '1', colors: ['B'], keywords: ['Flying'] },
  Dragon: { name: 'Dragon', typeLine: 'Creature — Dragon', power: '5', toughness: '5', colors: ['R'], keywords: ['Flying'] },
  Angel: { name: 'Angel', typeLine: 'Creature — Angel', power: '4', toughness: '4', colors: ['W'], keywords: ['Flying'] },
  Demon: { name: 'Demon', typeLine: 'Creature — Demon', power: '5', toughness: '5', colors: ['B'], keywords: ['Flying'] },
  Wurm: { name: 'Wurm', typeLine: 'Creature — Wurm', power: '6', toughness: '6', colors: ['G'] },
  Construct: { name: 'Construct', typeLine: 'Artifact Creature — Construct', power: '0', toughness: '0', colors: [], oracleText: 'This creature gets +1/+1 for each artifact you control.' },
  Copy: { name: 'Copy', typeLine: 'Creature', colors: [] },
  Eldrazi: { name: 'Eldrazi Spawn', typeLine: 'Creature — Eldrazi Spawn', power: '0', toughness: '1', colors: [], oracleText: 'Sacrifice this creature: Add {C}.' },
  Scion: { name: 'Eldrazi Scion', typeLine: 'Creature — Eldrazi Scion', power: '1', toughness: '1', colors: [], oracleText: 'Sacrifice this creature: Add {C}.' },
  Pest: { name: 'Pest', typeLine: 'Creature — Pest', power: '1', toughness: '1', colors: ['B', 'G'], oracleText: 'When this creature dies, you gain 1 life.' },
  Citizen: { name: 'Citizen', typeLine: 'Creature — Citizen', power: '1', toughness: '1', colors: ['G', 'W'] },
  Warrior: { name: 'Warrior', typeLine: 'Creature — Warrior', power: '1', toughness: '1', colors: ['W'] },
  Vampire: { name: 'Vampire', typeLine: 'Creature — Vampire', power: '1', toughness: '1', colors: ['B'], keywords: ['Lifelink'] },
  Myr: { name: 'Myr', typeLine: 'Artifact Creature — Myr', power: '1', toughness: '1', colors: [] },
  Golem: { name: 'Golem', typeLine: 'Artifact Creature — Golem', power: '3', toughness: '3', colors: [] },
  Plant: { name: 'Plant', typeLine: 'Creature — Plant', power: '0', toughness: '1', colors: ['G'] },
  Illusion: { name: 'Illusion', typeLine: 'Creature — Illusion', power: '1', toughness: '1', colors: ['U'] },
  Shard: { name: 'Shard', typeLine: 'Enchantment — Shard', colors: [], oracleText: '{2}, Sacrifice this enchantment: Scry 1, then draw a card.' },
  Incubator: { name: 'Incubator', typeLine: 'Artifact — Incubator', colors: [] },
  'Wicked Role': { name: 'Wicked', typeLine: 'Enchantment — Aura Role', colors: [], oracleText: 'Enchant creature\nEnchanted creature gets +1/+1.\nWhen this Aura is put into a graveyard from the battlefield, each opponent loses 1 life.' },
  'Monster Role': { name: 'Monster', typeLine: 'Enchantment — Aura Role', colors: [], oracleText: 'Enchant creature\nEnchanted creature gets +1/+1 and has trample.' },
  'Royal Role': { name: 'Royal', typeLine: 'Enchantment — Aura Role', colors: [], oracleText: 'Enchant creature\nEnchanted creature gets +1/+1 and has ward {1}.' },
  'Sorcerer Role': { name: 'Sorcerer', typeLine: 'Enchantment — Aura Role', colors: [], oracleText: 'Enchant creature\nEnchanted creature gets +1/+1 and has "{T}: Scry 1."' },
  'Cursed Role': { name: 'Cursed', typeLine: 'Enchantment — Aura Role', colors: [], oracleText: 'Enchant creature\nEnchanted creature has base power and toughness 1/1.' },
  'Virtuous Role': { name: 'Virtuous', typeLine: 'Enchantment — Aura Role', colors: [], oracleText: 'Enchant creature\nEnchanted creature gets +1/+1 for each enchantment you control.' },
  'Young Hero Role': { name: 'Young Hero', typeLine: 'Enchantment — Aura Role', colors: [], oracleText: 'Enchant creature\nEnchanted creature has "Whenever this creature attacks, if its toughness is 3 or less, put a +1/+1 counter on it."' },
};
